---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: nwserver-deploy
  namespace: nwapp
  labels:
    name: nwserver-deploy
    version: v1

spec:
  replicas: 3
  selector:
    matchLabels:
      name: nwserver-pod
      version: v1
  template:
    # pod template (describe the pod)
    metadata:
      name: nwserver-pod
      labels:
        name: nwserver-pod
        version: v1
    spec:
      containers:
      - name: nwserver-container
        image: akira87/mynorthwindserver:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: northwind-config
              key: db_host
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: northwind-config
              key: db_user
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: northwind-config
              key: server_port
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: northwind-secret
              key: db_password
        - name: INSTANCE_IP_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        ports:
          - name: app-port
            containerPort: 3000
---
apiVersion: v1
kind: Service

metadata:
  name: nwserver-svc
  namespace: nwapp
  labels:
    name: nwserver-svc
    version: v1

spec:
  type: LoadBalancer
  selector:
    name: nwserver-pod
    version: v1
  ports:
  - name: http
    port: 80
    targetPort: app-port